### ISSUE TITLE
Unable to use data from GLOBUS (.h5 files) as input to code

### ISSUE THREAD

**Issue by mcirclecvi** [rixez/pytorch_mri_variationalnetwork#1]
I have downloaded the data from [GLOBUS](https://auth.globus.org/p/login?redirect_name=Globus+Web+App&scope=urn%3Aglobus%3Aauth%3Ascope%3Aauth.globus.org%3Aview_identities+urn%3Aglobus%3Aauth%3Ascope%3Anexus.api.globus.org%3Agroups+urn%3Aglobus%3Aauth%3Ascope%3Atransfer.api.globus.org%3Aall&client_id=89ba3e72-768f-4ddb-952d-e0bb7305e2c7&response_type=token&viewlocale=en_US&redirect_uri=%2Fv2%2Foauth2%2Fauthorize%3Fclient_id%3D89ba3e72-768f-4ddb-952d-e0bb7305e2c7%26scope%3Durn%253Aglobus%253Aauth%253Ascope%253Aauth.globus.org%253Aview_identities%2520urn%253Aglobus%253Aauth%253Ascope%253Anexus.api.globus.org%253Agroups%2520urn%253Aglobus%253Aauth%253Ascope%253Atransfer.api.globus.org%253Aall%26response_type%3Dtoken%26redirect_uri%3Dhttps%253A%252F%252Fapp.globus.org%252Flogin%26redirect_name%3DGlobus%2520Web%2520App%26state%3Dstbaqam747%26viewlocale%3Den_US)  as mentioned in README. This consists of all .h5 files. Currently, I am working on Single Coil Knee dataset. There seems to be a missing link between what the code expects as input and the data downloaded from GLOBUS. 

1. Download single coil knee (train, test and val) data from GLOBUS
2. Change the root_dir to point to "knee folder"
3. run _python run_varnet.py_ on terminal
4. error:

----------------- Options ---------------
               activation: rbf                           
               batch_size: 1                             
                    epoch: 100                           
              error_scale: 1.0                           
             features_out: 24                            
                     gpus: 0                             
                loss_type: complex                       
              loss_weight: 1.0                           
                       lr: 0.0001                        
                     mode: train                         
                 momentum: 0.0                           
                     name: coronal_pd_fs                 
          num_act_weights: 31                            
               num_stages: 10                            
                optimizer: adam                          
                 root_dir: data/knee                     
         sampling_pattern: cartesian_with_os             
                 save_dir: exp/basic_varnet              
----------------- End -------------------
Traceback (most recent call last):
  File "run_varnet.py", line 46, in <module>
    dataset = KneeDataset(**args)
  File "/home/m/Documents/mri_variationalnetwork/pytorch_mri_variationalnetwork-master/data_utils.py", line 64, in _ _ init _ _
    self.mask = loadmat(str(self.mask_dir[0]))
IndexError: list index out of range

Any suggestions on how to proceed?

**Comment by rixez** [comment]
It seems like you downloaded different data from GLOBUS than the codes expect. The codes expect data to be the knee data in matlab .mat format. Since there are multiple projects in the GLOBUS link, I think you downloaded the data from the fastMRI folder instead of the knee folder.

Please try to download the correct data. I haven't tested the codes with the .h5 files so I'm not sure how to open and process them.
